# Generated by Django 4.2.1 on 2023-07-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_chapterdetail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChapterDetail',
            new_name='ChapterList',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='SubjectList',
        ),
    ]
