# Generated by Django 4.2.1 on 2023-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_chapterdetail_chapterlist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlist',
            name='chapter_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
