# Generated by Django 4.2.1 on 2023-07-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_subjectlist_chapter_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectlist',
            name='chapter_count',
            field=models.IntegerField(default=0),
        ),
    ]
