# Generated by Django 4.2.1 on 2023-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_subjectlist_chapter_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectlist',
            name='totatime',
            field=models.IntegerField(default=0),
        ),
    ]
