# Generated by Django 4.2.1 on 2023-07-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_subjectlist_totatime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectlist',
            old_name='totatime',
            new_name='totaltime',
        ),
    ]
